export const diplomaCourseList = [
  "Diploma in Accounting",
  "Diploma in Hotel Management",
  "Diploma in Retail Management.",
  "Diploma in Cooperative Management Course",
  "Diploma in Business Administration",
  "Diploma in Visual Communication",
  "Diploma in Engineering",
  "Diploma in OT Technician",
  "Diploma in Graphic Designing",
  "Diploma in Computer Engineering/Computer Applications",
  "Diploma in Biotechnology",
  "Diploma in Lab Technician Course",
  "Diploma in Data Science",
  "Diploma in Infection Control Course",
  "Diploma in Mechatronics",
  "Post Graduate Diploma in GIS And Remote Sensing",
  "Diploma in Banking and Finance.",
  "Diploma in Dialysis Technician Course",
  "Diploma in Interior Decoration",
  "Diploma in Automobile Engineering",
  "Diploma in Handloom Technology",
  "Diploma in Banking & Finance",
  "Diploma in Multimedia & Animation",
  "Diploma in Event Management",
  "Diploma in Business/Big Data Analytics",
  "Diploma in Mechanical Engineering",
  "Diploma in Multimedia and Animation Course",
  "Diploma in Ophthalmology",
  "Post Graduate Diploma in Yoga",
  "Diploma in Aeronautical Engineering",
  "Diploma in Marketing & Public Relations",
  "Diploma in Fashion Design",
  "Diploma in Computer Applications",
  "Diploma in Foreign Languages",
  "Diploma in Nutrition & Dietetics",
  "Advanced Diploma in Computer Application",
  "Diploma in Textile Design",
  "Diploma in Digital Marketing.",
  "Diploma in Web Designing",
  "Diploma in Homeopathic Medicine and Surgery",
  "Diploma in Economics",
  "Diploma in Electrical and Electronics Engineering",
  "Diploma in Financial Accounting Computer Course",
  "Diploma in Information Technology",
  "Diploma in Computer Engineering",
  "Diploma in Ayurvedic Pharmacy",
  "Post Graduate Diploma in Advertising",
  "Diploma in Library and Information Science",
  "Advanced Diploma in Fashion Design",
  "Post Graduate Diploma in Management [PGDM] (Management)",
  "Diploma in Electronics & Communication Engineering",
  "Diploma in Human Resource Management",
  "Diploma in Nursing Course",
  "Diploma in Animal Husbandry",
  "Diploma in Business Management.",
  "Diploma in Dermatology",
  "Diploma in Medical Lab Technology",
  "Post Graduate Diploma in Human Resource Management [PGDM] (HR)",
  "Diploma in Forensic Science",
  "Diploma in Nutrition andHealth Education",
  "Diploma in Textile Processing",
  "Post Graduate Diploma in Management [PGDM]",
  "Diploma in Marine Engineering",
  "Diploma in Foreign Trade/International Trade Management",
  "Diploma in Computer Programming",
  "Advanced Diploma in Interior Design",
  "Diploma in Biotechnology.",
  "Diploma in Homeopathy Course",
  "Diploma in Radiological Therapy",
  "Post Graduate Diploma in Management (PGDM) + Master of Business Administration (MBA)",
  "Diploma in Medical Imaging Technology Course Details",
  "Diploma in Plastic Technology",
  "Diploma in Tourism Studies",
  "Diploma in Travel and Tourism",
  "PG Diploma in Data Science & Artificial Intelligence",
  "Diploma in Culinary Arts",
  "Diploma in Graphic Design.",
  "Diploma in Physiotherapy",
  "Diploma in Banking and Finance",
  "Post Graduate Diploma in Management [PGDM] (Marketing)",
  "Diploma in Medical Lab Technology.",
  "Post Graduate Diploma in Intellectual Property Rights",
  "Post Graduate Diploma in Obstetrics & Gynaecology",
  "Diploma in Ceramic Technology",
  "Diploma in Nursing",
  "Diploma in Instrumentation Technology",
  "Diploma in Digital Marketing",
  "Diploma in Computer Science and Engineering",
  "Diploma in Apparel Design",
  "PG Diploma in Nutrition andDietetics Online Course",
  "Diploma in Chemical Engineering",
  "Diploma in Hotel Management.",
  "Diploma in Dental Mechanics",
  "Diploma in Acting",
  "Diploma in Photography",
  "Diploma in Financial Management",
  "Diploma in Biomedical Biotechnology",
  "Diploma in Leather Technology",
  "Diploma in Education Technology.",
  "Post Graduate Diploma in Cyber Law",
  "Diploma in Radiological Technology.",
  "Diploma in Fashion Designing",
  "Diploma in AC Mechanic Course",
  "Diploma in Labour Law Distance Education",
  "Diploma in Textile Technology (Knitting/Weaving/Spinning)",
  "Post Graduate Diploma in Forensic Science",
  "Diploma in Creative Writing.",
  "Post Graduate Diploma in Clinical Nutrition & Dietetics",
  "Diploma in Electrical Engineering",
  "Diploma in Programming",
  "Diploma in Food and Beverage Services Management",
  "Diploma in Web Designing Course",
  "Diploma in Tailoring",
  "Post Graduate Diploma in Computer Applications [PGDCA]",
  "Diploma in Electronics and Communication Engineering",
  "Diploma in Pharmacy [D.Pharma]",
  "Post Graduate Diploma in Accountancy",
  "Diploma in Production & Industrial Engineering",
  "Diploma in Agricultural Engineering",
  "Diploma in Garment Technology",
  "Diploma in Advertising.",
  "PGDEMA (Post-Graduate Diploma in Event Management and Activation)",
  "Diploma in Civil Engineering",
  "Diploma in Agriculture",
  "Diploma in Journalism and Mass Communication.",
  "Post Graduate Diploma in Labour Laws [PGDLL]",
  "Post Graduate Diploma in Human Resource Management (PGDHRM)",
  "Post Graduate Diploma in Data Science",
  "Diploma in Medical Field",
  "Diploma in Bakery and Confectionery",
  "Diploma in Horticulture",
  "Diploma in Architecture Assistantship",
  "Post Graduate Diploma in Business Analytics",
  "Post Graduate Diploma in Guidance & Counselling",
  "Diploma in Animation.",
  "Diploma in Interior Designing.",
  "Diploma in Dialysis Technology",
  "Diploma in Event Management",
  "Post Graduate Diploma in Business Administration (PGDBM)",
  "Diploma in Accounting and Finance.",
  "Diploma in Pathology Course",
  "Diploma in Computer Application Course",
  "Diploma in Electrical & Telecommunication Engineering",
  "Post Graduate Diploma in Bioinformatics [Pgdbi]",
  "Post Graduate Diploma in Journalism",
  "Diploma in IT",
  "Diploma in Clinical Research",
  "Diploma in Food Technology",
  "Diploma in Physiotherapy Course",
  "Diploma in Logistics and Supply Chain Management",
  "Diploma in Aviation",
  "Diploma in X-Ray Technology Course",
] as const;
