# Generated by Django 4.2 on 2023-10-22 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_department_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
