# Generated by Django 4.2 on 2023-10-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0004_countrymaster_statemaster_stateuniversitiesmaster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samaajmembermobilenumber",
            name="mobile_number",
            field=models.CharField(max_length=10),
        ),
    ]
